import { httpRouter } from "convex/server";
import { auth } from "./auth";
import { httpAction } from "./_generated/server";

const http = httpRouter();

auth.addHttpRoutes(http);

/**
 * Health check endpoint.
 */
http.route({
  path: "/api/health",
  method: "GET",
  handler: httpAction(async () => {
    return new Response(
      JSON.stringify({ status: "ok", timestamp: Date.now() }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      },
    );
  }),
});

/** CORS helper — Convex HTTP actions need explicit CORS for cross-origin browser requests. */
function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && origin.startsWith("http") ? origin : "*";
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, X-Profile-Upload-Trace",
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Max-Age": "86400",
  };
}

/** Helper: build a JSON Response with CORS headers. */
function jsonResponse(status: number, body: unknown, origin?: string | null) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin ?? null) },
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Customer Event Collector — receives behavioral events from the browser
// ─────────────────────────────────────────────────────────────────────────────

http.route({
  path: "/api/events",
  method: "OPTIONS",
  handler: httpAction(async (_ctx, request) => {
    const origin = request.headers.get("origin") || null;
    return new Response(null, { status: 204, headers: corsHeaders(origin) });
  }),
});

http.route({
  path: "/api/events",
  method: "POST",
  handler: httpAction(async (ctx, request) => {
    const traceId = `EVT-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
    const origin = request.headers.get("origin") || null;

    console.log(`[EVENT_COLLECTOR] [${traceId}] request received origin=${origin}`);

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return jsonResponse(400, { success: false, error: { code: "INVALID_BODY", message: "Invalid JSON body" } });
    }

    const { events } = body as { events?: Array<Record<string, unknown>> };
    if (!Array.isArray(events) || events.length === 0) {
      return jsonResponse(400, { success: false, error: { code: "MISSING_EVENTS", message: "No events provided" } });
    }

    console.log(`[EVENT_COLLECTOR] [${traceId}] received ${events.length} events`);

    let userId: string | null = null;
    try {
      const identity = await ctx.auth.getUserIdentity();
      if (identity) userId = identity.subject;
    } catch { /* anonymous OK */ }

    let inserted = 0;
    for (const event of events) {
      try {
        await ctx.runMutation("memoryEvents:track" as any, {
          type: String(event.type || "unknown"),
          productId: String(event.entityId || ""),
          value: String(event.value || ""),
        });
        inserted++;
      } catch (err) {
        console.log(`[EVENT_COLLECTOR] [${traceId}] event failed:`, err);
      }
    }

    console.log(`[EVENT_COLLECTOR] [${traceId}] complete inserted=${inserted}/${events.length}`);
    return jsonResponse(200, { success: true, inserted, total: events.length });
  }),
});

// ─────────────────────────────────────────────────────────────────────────────
// Media Upload — REMOVED
//
// R2 signed upload URLs are now generated by Convex "use node" actions
// (customer:getProfileImageUploadIntent, commerce:getProductImageUploadIntent)
// because HTTP actions cannot use "use node" / node:crypto.
//
// Frontend callers must use the Convex action API instead of this HTTP endpoint.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Customer Profile — get derived intelligence
// ─────────────────────────────────────────────────────────────────────────────

http.route({
  path: "/api/customer/profile",
  method: "OPTIONS",
  handler: httpAction(async (_ctx, request) => {
    const origin = request.headers.get("origin") || null;
    return new Response(null, { status: 204, headers: corsHeaders(origin) });
  }),
});

http.route({
  path: "/api/customer/profile",
  method: "GET",
  handler: httpAction(async (ctx, request) => {
    const traceId = `CP-${Date.now().toString(36)}`;

    let identity;
    try {
      identity = await ctx.auth.getUserIdentity();
    } catch {
      return jsonResponse(401, { success: false, error: { code: "UNAUTHORIZED" } });
    }
    if (!identity) {
      return jsonResponse(401, { success: false, error: { code: "UNAUTHORIZED" } });
    }

    console.log(`[CUSTOMER_PROFILE] [${traceId}] userId=${identity.subject}`);
    return jsonResponse(200, {
      success: true,
      profile: { userId: identity.subject, segment: "new", totalOrders: 0, totalSpent: 0 },
    });
  }),
});

export default http;
