import { mutation } from "./_generated/server";

type ProductData = {
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: string;
  imageUrl: string;
  inStock: boolean;
  rating?: number;
  reviewCount?: number;
  tags?: string[];
  featured?: boolean;
  reorderLevel: number;
  currentStock: number;
};

const products: ProductData[] = [
  {
    name: "Premium Wireless Headphones",
    description: "Immersive sound with active noise cancellation. 30-hour battery life.",
    price: 2999,
    originalPrice: 3999,
    category: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.8,
    reviewCount: 234,
    tags: ["wireless", "noise-cancelling", "audio"],
    featured: true,
    reorderLevel: 10,
    currentStock: 50,
  },
  {
    name: "Ultra-Slim Smartwatch",
    description: "Track your fitness, receive notifications. Sleek, water-resistant design.",
    price: 4999,
    originalPrice: 5999,
    category: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.6,
    reviewCount: 189,
    tags: ["smartwatch", "fitness", "wearable"],
    featured: true,
    reorderLevel: 8,
    currentStock: 35,
  },
  {
    name: "Minimalist Leather Backpack",
    description: "Full-grain leather with padded laptop compartment. Perfect for work.",
    price: 3499,
    originalPrice: 4499,
    category: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.9,
    reviewCount: 312,
    tags: ["backpack", "leather", "laptop"],
    featured: true,
    reorderLevel: 5,
    currentStock: 20,
  },
  {
    name: "Ceramic Pour-Over Coffee Set",
    description: "Hand-crafted ceramic dripper with thermal carafe.",
    price: 1899,
    originalPrice: 2499,
    category: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
    tags: ["coffee", "ceramic", "kitchen"],
    featured: true,
    reorderLevel: 12,
    currentStock: 40,
  },
  {
    name: "Running Performance Shoes",
    description: "Lightweight carbon-plate design for speed.",
    price: 5499,
    originalPrice: 6999,
    category: "Sports",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.8,
    reviewCount: 421,
    tags: ["running", "shoes", "sports"],
    featured: true,
    reorderLevel: 15,
    currentStock: 60,
  },
  {
    name: "Vintage Film Camera",
    description: "Classic 35mm film camera with manual controls.",
    price: 6999,
    category: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.4,
    reviewCount: 67,
    tags: ["camera", "film", "photography"],
    featured: false,
    reorderLevel: 3,
    currentStock: 12,
  },
  {
    name: "Organic Cotton Hoodie",
    description: "Sustainably made with organic cotton. Relaxed fit.",
    price: 2499,
    originalPrice: 2999,
    category: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f7b807ad?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.6,
    reviewCount: 203,
    tags: ["hoodie", "organic", "sustainable"],
    featured: true,
    reorderLevel: 10,
    currentStock: 45,
  },
  {
    name: "Wireless Mechanical Keyboard",
    description: "Hot-swappable switches, RGB backlight, dual-mode connectivity.",
    price: 3999,
    originalPrice: 4999,
    category: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.8,
    reviewCount: 312,
    tags: ["keyboard", "mechanical", "wireless"],
    featured: true,
    reorderLevel: 8,
    currentStock: 30,
  },
  {
    name: "Stainless Steel Water Bottle",
    description: "Double-wall vacuum insulation. Cold 24hrs, hot 12hrs.",
    price: 899,
    originalPrice: 1299,
    category: "Sports",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.7,
    reviewCount: 543,
    tags: ["bottle", "stainless", "insulated"],
    featured: false,
    reorderLevel: 20,
    currentStock: 100,
  },
  {
    name: "Ergonomic Office Chair",
    description: "Adjustable lumbar support, breathable mesh, 4D armrests.",
    price: 8999,
    originalPrice: 11999,
    category: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.5,
    reviewCount: 98,
    tags: ["chair", "ergonomic", "office"],
    featured: false,
    reorderLevel: 5,
    currentStock: 15,
  },
  {
    name: "Handmade Ceramic Planter",
    description: "Unique hand-thrown planter with drainage hole.",
    price: 1299,
    category: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.5,
    reviewCount: 87,
    tags: ["planter", "ceramic", "plants"],
    featured: false,
    reorderLevel: 8,
    currentStock: 25,
  },
  {
    name: "Travel Yoga Mat",
    description: "Lightweight, foldable mat with alignment markers.",
    price: 1699,
    originalPrice: 2199,
    category: "Sports",
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.3,
    reviewCount: 145,
    tags: ["yoga", "mat", "travel"],
    featured: false,
    reorderLevel: 10,
    currentStock: 30,
  },
  {
    name: "Polarized Aviator Sunglasses",
    description: "UV400 protection with lightweight titanium frames.",
    price: 2299,
    originalPrice: 2999,
    category: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.6,
    reviewCount: 278,
    tags: ["sunglasses", "polarized", "aviator"],
    featured: false,
    reorderLevel: 12,
    currentStock: 50,
  },
  {
    name: "Smart LED Desk Lamp",
    description: "Adjustable color temperature, wireless charging base.",
    price: 2799,
    originalPrice: 3499,
    category: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.4,
    reviewCount: 112,
    tags: ["lamp", "smart", "LED"],
    featured: false,
    reorderLevel: 6,
    currentStock: 22,
  },
  {
    name: "Canvas Low-Top Sneakers",
    description: "Classic canvas sneakers with vulcanized rubber sole.",
    price: 1799,
    originalPrice: 2299,
    category: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.5,
    reviewCount: 389,
    tags: ["sneakers", "canvas", "casual"],
    featured: true,
    reorderLevel: 15,
    currentStock: 55,
  },
  {
    name: "Portable Bluetooth Speaker",
    description: "360° sound with deep bass. IPX7 waterproof, 20-hour playtime.",
    price: 2199,
    originalPrice: 2799,
    category: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop",
    inStock: true,
    rating: 4.7,
    reviewCount: 267,
    tags: ["speaker", "bluetooth", "waterproof"],
    featured: false,
    reorderLevel: 10,
    currentStock: 40,
  },
];

export const seedProducts = mutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("products").first();
    if (existing) {
      return { message: "Products already seeded", count: 0 };
    }

    for (const product of products) {
      await ctx.db.insert("products", product);
    }

    return {
      message: "Products seeded successfully",
      count: products.length,
    };
  },
});
