/**
 * Velnox R2 Storage Service
 *
 * Cloudflare R2 is the primary media storage. This module provides:
 * - Signed upload URLs (browser uploads directly to R2, no binary through server)
 * - File deletion
 * - CDN URL generation
 * - Object key management
 *
 * Architecture:
 *   Browser → Backend (signed URL) → R2 (direct upload) → Confirm → Neon media record
 *
 * Required env vars (Convex deployment env):
 *   R2_ACCOUNT_ID       — Cloudflare account ID
 *   R2_ACCESS_KEY_ID    — R2 access key
 *   R2_SECRET_ACCESS_KEY — R2 secret key
 *   R2_BUCKET           — R2 bucket name
 *   R2_PUBLIC_DOMAIN    — Public CDN domain (e.g. "media.velshop.com")
 *
 * Never expose R2 credentials to the browser.
 * Presigned URLs are generated by the official AWS SDK presigner
 * (PutObjectCommand + getSignedUrl) — never hand-rolled SigV4.
 */

import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// ─── Configuration ──────────────────────────────────────────────────────────

export interface R2Config {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
  publicDomain: string;
}

export function getR2Config(): R2Config {
  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKeyId = process.env.R2_ACCESS_KEY_ID;
  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;
  const bucket = process.env.R2_BUCKET;
  const publicDomain = process.env.R2_PUBLIC_DOMAIN;

  if (!accountId || !accessKeyId || !secretAccessKey || !bucket || !publicDomain) {
    throw new Error(
      "R2 is not configured — set R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, " +
        "R2_BUCKET and R2_PUBLIC_DOMAIN in the project Keys/API keys UI.",
    );
  }
  return { accountId, accessKeyId, secretAccessKey, bucket, publicDomain };
}

export function isR2Configured(): boolean {
  return Boolean(
    process.env.R2_ACCOUNT_ID &&
      process.env.R2_ACCESS_KEY_ID &&
      process.env.R2_SECRET_ACCESS_KEY &&
      process.env.R2_BUCKET &&
      process.env.R2_PUBLIC_DOMAIN,
  );
}

function getS3Client(config: R2Config): S3Client {
  return new S3Client({
    region: "auto",
    endpoint: `https://${config.accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
    },
  });
}

// ─── Object Key Generation ──────────────────────────────────────────────────

export interface ObjectKeyParams {
  ownerType: "user" | "product" | "shop" | "order" | "system";
  ownerId: string;
  kind: string;
  filename: string;
}

/**
 * Generate a deterministic R2 object key.
 * Pattern: {ownerType}/{ownerId}/{kind}/{uuid}.{ext}
 */
export function generateObjectKey(params: ObjectKeyParams): string {
  const ext = params.filename.split(".").pop()?.toLowerCase() || "bin";
  const uuid = crypto.randomUUID();
  return `${params.ownerType}/${params.ownerId}/${params.kind}/${uuid}.${ext}`;
}

// ─── Signed Upload URL ──────────────────────────────────────────────────────

export interface SignedUploadUrl {
  uploadUrl: string;
  objectKey: string;
  cdnUrl: string;
  expiresAt: number;
}

/**
 * Generate a pre-signed PUT URL for direct browser-to-R2 upload.
 * The browser uploads directly to R2 — no binary bytes through the server.
 *
 * Signed headers are `content-type;host` — the browser PUT MUST send exactly
 * `Content-Type: <file.type>` and nothing else.
 *
 * @param objectKey — R2 key (use generateObjectKey)
 * @param contentType — MIME type of the file
 * @param expiresIn — URL validity in seconds (default 300 = 5 min)
 */
export async function getSignedUploadUrl(
  objectKey: string,
  contentType: string,
  expiresIn = 300,
): Promise<SignedUploadUrl> {
  const config = getR2Config();
  const uploadUrl = await getSignedUrl(
    getS3Client(config),
    new PutObjectCommand({
      Bucket: config.bucket,
      Key: objectKey,
      ContentType: contentType,
    }),
    { expiresIn },
  );

  // Security: never log the full presigned URL or signature.
  console.log(`[R2_PRESIGN] PUT host=${new URL(uploadUrl).hostname} key=${objectKey} expires=${expiresIn}s`);

  return {
    uploadUrl,
    objectKey,
    cdnUrl: `${config.publicDomain}/${objectKey}`,
    expiresAt: Date.now() + expiresIn * 1000,
  };
}

// ─── File Deletion ──────────────────────────────────────────────────────────

/**
 * Delete an object from R2 via the official AWS SDK.
 */
export async function deleteR2Object(objectKey: string): Promise<void> {
  const config = getR2Config();
  try {
    await getS3Client(config).send(new DeleteObjectCommand({ Bucket: config.bucket, Key: objectKey }));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (!/NoSuchKey|NotFound|404/i.test(msg)) {
      console.error(`[R2] DELETE failed key=${objectKey}: ${msg.slice(0, 200)}`);
      throw new Error(`R2 delete failed: ${msg}`);
    }
  }
}

// ─── URL Helpers ────────────────────────────────────────────────────────────

/** Get the public CDN URL for an object key. */
export function getCdnUrl(objectKey: string): string {
  const config = getR2Config();
  return `${config.publicDomain}/${objectKey}`;
}

/** Get a transformed CDN URL (for image resizing via CDN). */
export function getTransformedCdnUrl(
  objectKey: string,
  transform: { width?: number; height?: number; quality?: number },
): string {
  const base = getCdnUrl(objectKey);
  const params = new URLSearchParams();
  if (transform.width) params.set("w", String(transform.width));
  if (transform.height) params.set("h", String(transform.height));
  if (transform.quality) params.set("q", String(transform.quality));
  const qs = params.toString();
  return qs ? `${base}?${qs}` : base;
}
